version: '2'

services:

  api-service:
    container_name: moda-api-service
    build: .
    ports:
      - 8000:8000 # expose ports - HOST:CONTAINER
    links:
      - db-service
    depends_on:
      - db-service
    environment:
      - MONGO_URL=mongodb://db-service:27017/moda
      - NODE_ENV=production
      - SESSION_SECRET=changeme

#  web-service:
#    container_name: moda-web-service
#    build: ./client
#    ports:
#     - 5000:5000
#    links:
#      - api-service
#    depends_on:
#      - api-service
#    environment:
#      - REACT_APP_API_URL=http://api-service:8000

  db-service:
    container_name: moda-db-service
    image: mongo:latest
    ports:
     - 27017:27017
